apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc-pod
  template:
    metadata:
      labels:
        app: webmvc-pod
    spec:
      containers:
      - name: webmvc-container
        image: sandeepsoni/eshop-webapp
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: CatalogUrl
          valueFrom:
            configMapKeyRef:
              name: shopping-app-config
              key: CATALOG_URL
        - name: CartUrl
          valueFrom:
            configMapKeyRef:
              name: shopping-app-config
              key: CART_URL
        - name: IdentityServerUrl
          valueFrom:
            configMapKeyRef:
              name: shopping-app-config
              key: IDENTITY_SERVER_URL
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: webmvc-srv
spec:
  type: LoadBalancer
  selector:
    app: webmvc-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
