apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis-container
        image: redis
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: redis-volume 
      volumes:
      - name: redis-volume
        hostPath:
          path: /
          type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: redis-srv
spec:
  type: ClusterIP 
  selector:
    app: redis-pod
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
