apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-pod
  template:
    metadata:
      labels:
        app: catalog-pod
    spec:
      containers:
      - name: catalog-container
        image: sandeepsoni/eshop-catalog
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__ProductCatalogApiContext
          valueFrom:
            secretKeyRef:
              key: database_sqlserver_conn_string
              name: shopping-app-secret

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-srv
spec:
  type: ClusterIP
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
