apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
      - name: gateway-container
        image: sandeepsoni/eshop-gateway
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  type: ClusterIP 
  selector:
    app: gateway-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
